version: '3.3'

volumes:
  db_data:

services:
  db:
    image: postgres:14-alpine
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  web:
    build:
      context: ../quizz/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/music
    ports:
      - 8000:8000
    depends_on:
      - db