# Generated by Django 3.2 on 2023-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_quiz',
            fields=[
                ('question', models.CharField(max_length=256)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=256)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
